== Conventions

=== UML notation

Diagrams using the Unified Modeling Language (UML) static structure diagram, as described in Subclause 5.2 of OGC Web Service Commons [OGC 06-121r9], adhere to the following conventions:

* UML elements having a package name of “GML” are those defined in the UML model of GML 3.2.1 [2];
* UML elements having a package name of “SWE Common” are those defined in the UML model of SWE Common 2.0 [4]; and
* UML elements not qualified with a package name, or with “CIS”, are those defined in this standard.

Further, in any class where an attribute name or association role name is identical to a name in some superclass the local definition overrides the superclass definition.

=== Namespace prefix conventions

UML diagrams and XML code fragments adhere to the namespace conventions shown in Table 2. The namespace prefixes used in this document are *not* normative and are merely chosen for convenience. The namespaces to which the prefixes correspond are normative, however.

Whenever a data item from a CIS-external namespace is referenced this constitutes a *normative dependency* on the data structure imported together with all requirements defined in the namespace referenced.

.Namespace mapping conventions
|===
h| UML prefix h| GML prefix h| Namespace URL h| Description
| CIS | cis | http://www.opengis.net/cis/1.1[http://www.opengis.net/cis/1.1] | Coverage Implementation Schema 1.1
| CIS10 | cis10 | http://www.opengis.net/gmlcov/1.0[http://www.opengis.net/gmlcov/1.0]&nbsp; | Coverage Implementation Schema 1.0
| GML | gml | http://www.opengis.net/gml/3.2[http://www.opengis.net/gml/3.2] | GML 3.2.1
| GML33 | gml33 | http://www.opengis.net/gml/3.3[http://www.opengis.net/gml/3.3] | GML 3.3
| SWE Common | swe | http://www.opengis.net/swe/2.0[http://www.opengis.net/swe/2.0] | SWE Common 2.0
| SML | sml | http://www.opengis.net/sensorml/2.0[http://www.opengis.net/sensorml/2.0] | SensorML 2.0

|===
